name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Ejecutar script en bash
      run: |
        for i in {1..10}
        do
            echo "Hola Mundo $i"
        done
